import { Student, PaymentRecord, GroupDays, GradeName } from "../types";

export interface ParentAccount {
  studentBarcode: string;
  studentName?: string;
  linkedBarcodes: string[];
  parentPhone: string;
  password: string;
  status: "active" | "disabled" | "deleted";
  createdAt: string;
  updatedAt?: string;
  activatedAt?: string;
  deletedAt?: string;
  reason?: string;
  lastLoginAt?: string;
  fcmToken?: string;
}

export interface ParentChatMessage {
  id: string;
  chatId: string; // The primary student barcode for this conversation thread
  sender: "parent" | "admin";
  senderName: string;
  text: string;
  timestamp: number;
  timeFormatted: string;
  isRead: boolean;
  status?: "SENT" | "DELIVERED" | "READ";
  senderRole?: "supervisor" | "parent";
}

export interface AdminPortalSettings {
  adminBarcode: string;
  adminPassword: string;
  adminPhone?: string;
  pushNotificationsEnabled: boolean;
  soundAlertsEnabled: boolean;
  updatedAt?: string;
}

export interface AdminActivityLog {
  id: string;
  type: "activate" | "disable" | "enable" | "delete" | "edit" | "batch_activate" | "self_register";
  studentBarcode: string;
  studentName: string;
  timestamp: number;
  timeFormatted: string;
  details: string;
}

export type PortalUserRole = "parent" | "admin" | null;

export interface PortalSession {
  role: PortalUserRole;
  barcode: string;
  currentStudentBarcode?: string;
  account?: ParentAccount;
  token?: string;
}

export type ParentPortalTab =
  | "dashboard"
  | "attendance"
  | "financials"
  | "exams"
  | "homework"
  | "chat"
  | "profile";

export type AdminPortalTab =
  | "accounts"
  | "chats"
  | "settings";

export interface AttendanceScheduleLog {
  date: string;
  dayName: string;
  status: "حضور" | "تأخير" | "غائب" | "إذن" | "غير محدد" | "لم ترصد";
  timeRecorded?: string;
  isOfficialScheduledDay: boolean;
  isSubstituteDay: boolean; // Cross-group replacement attendance
  isAutoGenerated?: boolean; // Reserved schedule slot where attendance was unrecorded
  note?: string;
}

export interface HomeworkLogItem {
  id: string;
  date: string;
  status: "مكتمل" | "ناقص" | "لم يحل" | "معفى";
  pointsDelta: number;
  notes?: string;
}

export interface DelayRecordItem {
  date: string;
  time: string;
  delayMinutes: number;
  note?: string;
}
